name: Check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3.8.2
      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: http://nix-builder.qrtz.lab:8080
          cache: homelab
          token: ${{ secrets.ATTIC_TOKEN }}
      - name: Flake check
        run: nix flake check
      # - name: Flake checka
      #   uses: workflow/nix-shell-action@v3.4.0
      #   with:
      #     flakes: github:Mic92/nix-fast-build
      #     script: nix-fast-build --no-nom --skip-cached --attic-cache homelab
